version: '2.1'

services:
  
  eventos-db:
    build: ./db
    environment:
      MYSQL_DATABASE: Events
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      DATABASE_HOST: eventos-db
  
  eventos-ms:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_HOST: eventos-db
      MYSQL_PORT: 3301
      MYSQL_DATABASE: Events
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3003:3000"
    depends_on:
      - eventos-db
    restart: on-failure
